version: '2.1'

services:
  harveymoj:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctssbox.azurecr.io/labs/harveymoj
    ports:
      - $SERVER_PORT:$SERVER_PORT
